name: BlueDream-Lottery
version: 1.1.6
main: com.bluedream.lottery.BlueDreamLottery
api-version: '1.20'
softdepend: [Vault, PlayerPoints, PlaceholderAPI]
commands:
  lottery:
    description: 抽奖主指令
    aliases: [lt, bdl]
permissions:
  bluedream.lottery.admin:
    description: 抽奖管理权限
    default: op
  bluedream.lottery.use:
    description: 抽奖使用权限
    default: true
